CREATE TABLE "mytable" (
  "SELECT * FROM Customer;" text
);

INSERT INTO "mytable" ("SELECT * FROM Customer;")
VALUES
('DELETE FROM Customer'),
('WHERE Satisfaction = "";'),
('SELECT * FROM Customer'),
('ORDER BY Total_Spend DESC'),
('LIMIT 10;'),
('SELECT * FROM Customer'),
('ORDER BY Items_Purchased DESC'),
('LIMIT 10;'),
('SELECT Age'),
('FROM Customer'),
('GROUP BY Age'),
('ORDER BY Age;'),
('SELECT Membership_Type'),
('FROM Customer'),
('Group BY Membership_Type;'),
('SELECT AVG(Last_Purchase) FROM Customer;'),
('SELECT City'),
('FROM Customer'),
('GROUP BY City;'),
('SELECT AVG(Items_Purchased) FROM Customer;'),
('SELECT Discount_Applied'),
('FROM Customer'),
('GROUP BY Discount_Applied;'),
('SELECT Average_Rating'),
('FROM Customer'),
('GROUP BY Average_Rating'),
('ORDER BY Average_Rating DESC;'),
('SELECT Membership_Type'),
('FROM Customer'),
('Group By Membership_Type'),
('ORDER BY AVG(Average_Rating) DESC;'),
('SELECT Satisfaction'),
('FROM Customer'),
('GROUP BY Satisfaction'),
('ORDER BY AVG(Last_Purchase);'),
('SELECT City'),
('FROM Customer'),
('GROUP BY City'),
('SELECT Age'),
('FROM Customer'),
('GROUP BY Age');
